### ISSUE TITLE
Driver Control Unit Redesign

### ISSUE THREAD

**Issue by Austin8462** [Illinois-State-Solar-Car/Driver-Control#7]
Redesign of the driver control board to implement a 12v pedal input, and 2 different connectors

**Comment by Austin8462** [comment]
Found a potential option for [Deutsch connector replacement.](https://www.te.com/usa-en/product-DT13-08PC.html) for the PCB side of things. -- 8 pin (2x4) which is fine since with our current D9 connector, we have duplicate pins.

**Comment by Austin8462** [comment]
After looking through EasyEDA more, there is not much in the library for 8 pin Deutsch compared to [12 pin connector -](https://www.te.com/usa-en/product-DTF13-12PC.html)- switching to 12 pin for now.

Both connectors being considered for PCB side have been right-angled mounting due to the way they'll end up in the car to help with cable flow.

**Comment by fabio-gustav** [comment]
Tested the voltage divider concept with 2k and 750 ohms. It topped out at about 11.8 volts and didn't blow up when I "simulated a voltage spike" and gave it 13 volts. I might tweak the resistors a little bit but it should be good.

**Comment by Austin8462** [comment]
Ref to Driver Screen:

After looking through EasyEDA more, there is not much in the library for 8 pin Deutsch compared to [12 pin connector -](https://www.te.com/usa-en/product-DTF13-12PC.html)- switching to 12 pin for now.

Both connectors being considered for PCB side have been right-angled mounting due to the way they'll end up in the car to help with cable flow.

**Comment by Austin8462** [comment]
Board re-design complete & ready for review. Original D9 connector has been split into two 12P Deutsch, one for Motor Controller and the other to go to the front of the car (DC Screen, Pedal, GP pin access). Added pin labels to bottom silk layer for easy identification once connector is attached.

**Comment by Austin8462** [comment]
Back to in progress to edit the connector orientation 

Also need to find the correct gray Deutsch connectors

**Comment by Austin8462** [comment]
Orientation edited, will find the correct series of Deutsch connectors at a later time.

**Comment by Austin8462** [comment]
Need mounting pattern from OLD DCU to NEW DCU

**Comment by Austin8462** [comment]
SHLD bounded to GND copper layers - SHLD GND unused since the car is all one singular ground plane

Boards in cart to be hopefully ordered tomorrow

**Comment by Austin8462** [comment]
sdf

**Comment by Austin8462** [comment]
Rev2 boards were ordered.

**Comment by Austin8462** [comment]
I done diddly goofed the connector sizing....
