### ISSUE TITLE
Wire Motor Control Panel

### ISSUE THREAD

**Issue by fabio-gustav** [Illinois-State-Solar-Car/Driver-Control#8]
Mounting the Motor Control panel, wiring motor controller and driver control unit.

**Comment by Austin8462** [comment]
Work on motor controller panel has begun. Mounting holes for the MC & DCU have been drilled and a mounting method has been decided on. Sufficient space was left for the Portenta squirrel board. Will have to collab with Jim/Mech to get a mounting bracket designed to provide support of the panel overhang.

**Comment by Austin8462** [comment]
MC and DCU have both been mounted onto fiberglass panel. Panel has been securely mounted into the car. 6p deutsch between DCU & MC is made and connected, DCU --> Front of car is still being worked on, wire is run but final connections need to be made (depends partly on dashboard being done.)
